/*!
 * Jade - runtime
 * Copyright(c) 2010 TJ Holowaychuk <tj@vision-media.ca>
 * MIT Licensed
 */
/**
 * @license RequireJS domReady 1.0.0 Copyright (c) 2010-2011, The Dojo Foundation All Rights Reserved.
 * Available via the MIT or new BSD license.
 * see: http://github.com/jrburke/requirejs for details
 */
define("jadeRuntime",[],function(){var a=function(a){return Array.isArray||(Array.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)}),Object.keys||(Object.keys=function(a){var b=[];for(var c in a)a.hasOwnProperty(c)&&b.push(c);return b}),a.attrs=function(c,d){var e=[],f=c.terse;delete c.terse;var g=Object.keys(c),h=g.length;if(h){e.push("");for(var i=0;i<h;++i){var j=g[i],k=c[j];"boolean"==typeof k||null==k?k&&(f?e.push(j):e.push(j+'="'+j+'"')):0==j.indexOf("data")&&"string"!=typeof k?e.push(j+"='"+JSON.stringify(k)+"'"):"class"==j&&Array.isArray(k)?e.push(j+'="'+a.escape(k.join(" "))+'"'):d[j]?e.push(j+'="'+a.escape(k)+'"'):e.push(j+'="'+k+'"')}}return e.join(" ")},a.escape=function(b){return String(b).replace(/&(?!\w+;)/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")},a.rethrow=function(b,c,d){if(!c)throw b;var e=3,f=require("fs").readFileSync(c,"utf8"),g=f.split("\n"),h=Math.max(d-e,0),i=Math.min(g.length,d+e),e=g.slice(h,i).map(function(a,b){var c=b+h+1;return(c==d?"  > ":"    ")+c+"| "+a}).join("\n");throw b.path=c,b.message=(c||"Jade")+":"+d+"\n"+e+"\n\n"+b.message,b},a}({});return a}),define("templates/sample",["jadeRuntime"],function(jade){return function anonymous(locals,attrs,escape,rethrow){var attrs=jade.attrs,escape=jade.escape,rethrow=jade.rethrow,buf=[];with(locals||{}){var interp;buf.push("<p> \nHello <b>"+escape((interp=locals.name||"World")==null?"":interp)+"</b>!</p>")}return buf.join("")}}),define("domReady",[],function(){function i(a){for(var b=0,d;d=a[b];b++)d(c)}function j(){var a=d,c=e;b&&(a.length&&(d=[],i(a)),f.resourcesDone&&c.length&&(e=[],i(c)))}function k(){b||(b=!0,h&&clearInterval(h),j())}function l(a){return b?a(c):d.push(a),l}var a=typeof window!="undefined"&&window.document,b=!a,c=a?document:null,d=[],e=[],f=requirejs||require||{},g=f.resourcesReady,h;return"resourcesReady"in f&&(f.resourcesReady=function(a){g&&g(a),a&&j()}),a&&(document.addEventListener?(document.addEventListener("DOMContentLoaded",k,!1),window.addEventListener("load",k,!1)):window.attachEvent&&(window.attachEvent("onload",k),self===self.top&&(h=setInterval(function(){try{document.body&&(document.documentElement.doScroll("left"),k())}catch(a){}},30))),document.readyState==="complete"&&k()),l.withResources=function(a){return b&&f.resourcesDone?a(c):e.push(a),l},l.version="1.0.0",l.load=function(a,b,c,d){d.isBuild?c(null):l(c)},l}),require({baseUrl:"/js"}),require(["templates/sample","domReady!"],function(a){var b=document.getElementById("rendered_in_client");b.innerHTML="About to run renderer";var c=a({});b.innerHTML=c.replace(/</g,"&lt;").replace(/>/g,"&gt;")}),define("main",function(){})